name: messgram
description: Telegram style chat app with Appwrite and Inline Ads.
publish_to: 'none'
version: '1.0.0+1'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^11.0.0
  http: ^1.2.0

flutter:
  uses-material-design: true
